### ISSUE TITLE
Module.yaml Environments Types

### ISSUE THREAD

**Issue by kubagrzelak** [weeve-modules/serial-ingress#13]
For now we need this module to support V0. If you use `options` then you need to set the type to `enum`. Otherwise it is not going to work in the UI. Environments values parsed from `options` will be read by your code as strings, so if you need to use integers somewhere in the code you need to cast them.

In V1 you will need type `select` or `multiple` to use `options`, but these changes will be made to all modules after we introduce the new module boilerplate.

**Comment by GhasBarbouchi** [comment]
ok alright.
